[package]
name = "catsay_gui"
version = "0.1.0"
authors = ["Yasin Radi <yasin.ben.hamman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.15.0"
